## Quickstart tutorial

### Basics
The main object of **NumPy** is the homogeneous multidimensional array. It is a table of elements(usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy, dimensions are called axes.

NumPy's array class is called **ndarray**. The more important attributes of **ndarray object** are:
1. **ndarray.ndim**  the number of axes(dimensions) of the array.
2. **ndarray.shape**  the dimensions of the array. A tuple of integers containing (rows, columns).
3. **ndarray.size**  the total number of elements in the array. This is equal to the product of the elements of the shape.
4. **ndarray.dtype**  an object describing the type of elements in the array.
5. **ndarray.itemsize**  the size in bytes of each element of the array.
6. **ndarray.data**  the buffer containing the actual elements of the array. Normally, we don't need to use this attribute because we will access the elements in an array using indexing facilities.

### Examples

In [1]:
import numpy as np
a = np.arange(15).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [2]:
a.ndim

2

In [3]:
a.shape

(5, 3)

In [4]:
a.size

15

In [5]:
a.dtype

dtype('int64')

In [6]:
a.itemsize

8

In [7]:
a.data

In [8]:
a.data

In [9]:
type(a)

numpy.ndarray

In [10]:
b = np.array([6, 7, 8])

In [11]:
b

array([6, 7, 8])

In [12]:
type(b)

numpy.ndarray

### Array Creation


**There are several ways to create arrays:**

Creating an array from a regular python list or tuple using the array function. The type of the resulting array is deduced from the type of elements in the sequences.

In [13]:
aa = np.array([2, 3, 4])
aa

array([2, 3, 4])

In [14]:
aa.dtype

dtype('int64')

In [15]:
bb = np.array([1.2, 3.5, "abc"])
bb

array(['1.2', '3.5', 'abc'], dtype='<U32')

**U32** is a string data type in Python.U refers to unicode strings.

In [16]:
cc = np.array([1.2, 3.5, 4.1])
cc

array([1.2, 3.5, 4.1])

In [17]:
cc.dtype

dtype('float64')

A frequrent error consists in calling **arrays** with multiple numeric arguments, rather than providing a single list of numbers as an argument.<br>
    a = np.array(1, 2, 3, 4) --- **Wrong**<br>
    a = np.array( [1, 2, 3, 4] ) --- **Right**

**Array** transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays and so on.

In [18]:
bbb = np.array([(1.5, 2, 3), (4, 5, 6)])
bbb

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [19]:
bbb.ndim

2

In [20]:
bbb.shape

(2, 3)

In [21]:
bbbb = np.array([[(1.5, 2, 3), (4, 5, 6)],[(3, 1, 7), (11, 9.1, 3.7)]])
bbbb

array([[[ 1.5,  2. ,  3. ],
        [ 4. ,  5. ,  6. ]],

       [[ 3. ,  1. ,  7. ],
        [11. ,  9.1,  3.7]]])

In [22]:
bbbb.ndim

3

In [23]:
bbbb.shape

(2, 2, 3)

**The type of the array can also be specified at creation time.**

In [24]:
ccc = np.array([[1, 2], [3,4]], dtype =  complex)
ccc

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Often the elements of an array are originally unknown but it's size is known. **Hence, NumPy offers several functions to create arrays with initial placeholder content.** These minimize the necessity of growing arrays, an expensive operation.<br>
The function **zeros, ones, empty** can be seen in the example below. the default data type for these is **float64**

In [25]:
np.zeros((3,4)) # creates an array full of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((2,5), dtype = np.int16) # creates an array full of ones.

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [27]:
np.empty((2,3))  # creates an array whose initial content is random and depends on the state of the memory.

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

To create sequences of numbers, NumPy provides a function analogous to **range** that returns arrays instead of lists.

In [28]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [29]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When **arange** is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use **linspace** function, that uses an argument about the number of elements we want, instead of the step.

In [30]:
np.linspace(0, 2, 9) # 9 numbers between 0 to 2.

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [31]:
from numpy import pi
x = np.linspace(0, 2*pi, 100) # useful to evaluate function at lots of points

In [32]:
f = np.sin(x)

**Miscellaneous functions: zeros_like, ones_like, empty_like, np.random.RandomState.rand, randn, fromfunction, fromfile**

In [33]:
np.zeros_like(ccc) # returns an array of zeros with same shape and type as a given array.

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

In [34]:
np.ones_like(bbbb) # returns an array of ones with the same shape and type as a given array.

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [36]:
np.empty_like(ccc) # returns a new array of same shape and type as a given array 

array([[0.25+0.5j, 0.75+1.j ],
       [1.25+1.5j, 1.75+2.j ]])

In [37]:
np.arange(0, 9, 1, dtype = int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

The in-built **range** function of Python generates integers that have arbitrary size whereas, **arange** produces numpy.int32 or numpy.int64 numbers.

In [39]:
 np.fromfunction(lambda i, j : i, (2,2), dtype = float) # constructs an array by executing a function over each
                                                        #coordinate

array([[0., 0.],
       [1., 1.]])

**np.fromfile** constructs an array from a data in a text or binary file.

### Printing Arrays

When an array is printed, NumPy displays it as a nested list:
1. the last axis is printed from left to right.
2. the second-to-last is printed from top to bottom.
3. the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

**1-D arrays are printed as rows, 2-Ds as matrices and 3-Ds as lists of matrices.**

In [41]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [43]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
c = np.arange(72).reshape(2,3,4,3)
c

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]],


       [[[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]],

        [[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]]]])

If an array is too large to be printed, NumPy automatically skips the central part of the array and onluy prints the corners.

In [47]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [48]:
print(np.arange(10000).reshape(1000,10))

[[   0    1    2 ...    7    8    9]
 [  10   11   12 ...   17   18   19]
 [  20   21   22 ...   27   28   29]
 ...
 [9970 9971 9972 ... 9977 9978 9979]
 [9980 9981 9982 ... 9987 9988 9989]
 [9990 9991 9992 ... 9997 9998 9999]]


To disbale this behaviour and force NumPy to print the entire array, you can chanhge the printing options using **set_printoptions** 

In [50]:
import sys
np.set_printoptions(threshold = sys.maxsize)

### Basic Operations

Arithmetic operators on arrays apply **elementwise**. A new array is cfreated and filled with the result.

In [52]:
a = np.array([20,30,40,50])
b = np.arange(4)

In [53]:
c = a - b
c

array([20, 29, 38, 47])

In [54]:
b**2

array([0, 1, 4, 9])

In [55]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [56]:
a<35

array([ True,  True, False, False])